export const COLOR_MAP = {
    'Severe Thunderstorm Warning': '#FFA500',
    'Flash Flood Warning': '#8B0000',
    'Severe Weather Statement': '#00FFFF',
    'Evacuation Immediate': '#7FFF00',
    'Special Marine Warning': '#FFA500',
    'Dust Storm Warning': '#FFE4C4',
    'Flood Warning': '#00FF00',
    'Extreme Heat Warning': '#C71585',
    'Severe Thunderstorm Watch': '#DB7093',
    'Red Flag Warning': '#FF1493',
    'Heat Advisory': '#FF7F50',
    'Flood Advisory': '#00FF7F',
    'Small Craft Advisory': '#D8BFD8',
    'Dust Advisory': '#BDB76B',
    'Hazardous Seas Warning': '#D8BFD8',
    'Wind Advisory': '#D2B48C',
    'Rip Current Statement': '#40E0D0',
    'Beach Hazards Statement': '#40E0D0',
    'Flood Watch': '#2E8B57',
    'Extreme Heat Watch': '#800000',
    'Fire Weather Watch': '#FFDEAD',
    'Special Weather Statement': '#FFE4B5',
    'Marine Weather Statement': '#FFEFD5',
    'Air Quality Alert': '#808080',
    'Hydrologic Outlook': '#90EE90',
    'Tornado Warning': '#FF0000',
    'Tornado Watch': '#FFFF00',
    'Flash Flood Statement': '#8B0000',
    'Flood Statement': '#00FF00',
    'Hydrologic Statement': '#00FF7F',
    'High Wind Warning': '#DAA520',
    'High Wind Watch': '#B8860B',
    'Excessive Heat Warning': '#C71585',
    'Excessive Heat Watch': '#800000',
    'Freeze Warning': '#483D8B',
    'Freeze Watch': '#00FFFF',
    'Dense Fog Advisory': '#708090',
    'Dense Smoke Advisory': '#F0E68C',
    'Blowing Dust Advisory': '#BDB76B',
    'Air Stagnation Advisory': '#808080',
    'Hurricane Force Wind Warning': '#CD5C5C',
    'Hurricane Force Wind Watch': '#9932CC',
    'Storm Warning': '#9400D3',
    'Storm Watch': '#EE82EE',
    'Gale Warning': '#DDA0DD',
    'Gale Watch': '#FFC0CB',
    'Marine Dense Fog Advisory': '#708090',
    'Hurricane Warning': '#DC143C',
    'Hurricane Watch': '#FF00FF',
    'Tropical Storm Warning': '#B22222',
    'Tropical Storm Watch': '#F08080',
    'Extreme Wind Warning': '#FF1493',
    'Hurricane Statement': '#FFFF00',
    'Coastal Flood Warning': '#228B22',
    'Coastal Flood Watch': '#66CDAA',
    'Coastal Flood Advisory': '#7CFC00',
    'Coastal Flood Statement': '#6B8E23',
    'High Surf Warning': '#228B22',
    'High Surf Advisory': '#BA55D3',
    'Fire Danger Statement': '#E9967A',
    'Extreme Cold Warning': '#B0C4DE',
    'Extreme Cold Watch': '#5F9EA0',
    'Cold Weather Advisory': '#AFEEEE',
    'Winter Storm Warning': '#FF69B4',
    'Ice Storm Warning': '#8B008B',
    'Winter Storm Watch': '#4682B4',
    'Winter Weather Advisory': '#7B68EE',
    'Blizzard Warning': '#FF4500',
    'Civil Emergency': '#FFB6C1',
    'Child Abduction Emergency': '#FFD700',
    'Civil Danger Warning': '#FFB6C1',
    'Earthquake Warning': '#8B4513',
    'Local Area Emergency': '#C0C0C0',
    'Law Enforcement Warning': '#C0C0C0',
    '911 Telephone Outage': '#C0C0C0',
    'Hazardous Materials Warning': '#4B0082',
    'Nuclear Hazard Warning': '#4B0082',
    'Radiological Hazard Warning': '#4B0082',
    'Fire Warning': '#A0522D',
    'Shelter in Place Warning': '#FA8072',
    'Volcano Warning': '#696969',
    'Tsunami Warning': '#FD6347',
    'Tsunami Watch': '#FF00FF',
    'Tsunami Advisory': '#D2691E',
    'Tsunami Information Statement': '#FFCCFF',
    'Short Term Forecast': '#98FB98',
    'Hazardous Weather Outlook': '#EEE8AA',
}

export const FALLBACK_COLOR = '#9999ff'

export const MAP_CONFIG = {
    container: 'map',
    style: 'https://basemaps.cartocdn.com/gl/voyager-gl-style/style.json',
    center: [-98.5795, 39.8283],
    zoom: 3,
}

export const LAYER_STYLES = {
    countyBoundaries: {
        'line-color': '#808080',
        'line-width': 0.5,
        'line-opacity': 0.5,
    },
    stateBoundaries: {
        'line-color': '#000000',
        'line-width': 1,
        'line-opacity': 1,
    },
    alertPolygons: {
        'fill-opacity': 1,
    },
    countyFills: {
        'fill-opacity': 1,
    },
}
