const COLOR_MAP = {
    'Severe Thunderstorm Warning': '#FFA500',
    'Flash Flood Warning': '#8B0000',
    'Severe Weather Statement': '#00FFFF',
    'Evacuation Immediate': '#7FFF00',
    'Special Marine Warning': '#FFA500',
    'Flood Warning': '#00FF00',
    'Extreme Heat Warning': '#C71585',
    'Severe Thunderstorm Watch': '#DB7093',
    'Red Flag Warning': '#FF1493',
    'Heat Advisory': '#FF7F50',
    'Flood Advisory': '#00FF7F',
    'Small Craft Advisory': '#D8BFD8',
    'Hazardous Seas Warning': '#D8BFD8',
    'Wind Advisory': '#D2B48C',
    'Rip Current Statement': '#40E0D0',
    'Beach Hazards Statement': '#40E0D0',
    'Flood Watch': '#2E8B57',
    'Extreme Heat Watch': '#800000',
    'Fire Weather Watch': '#FFDEAD',
    'Special Weather Statement': '#FFE4B5',
    'Marine Weather Statement': '#FFEFD5',
    'Air Quality Alert': '#808080',
    'Hydrologic Outlook': '#90EE90',
}
